# Generated by Django 2.0.12 on 2019-05-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Directiva',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='logo-league/')),
                ('email', models.EmailField(default='contact@micorreo.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=25, null=True)),
                ('stature', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField()),
                ('sex', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='Masculino', max_length=15)),
                ('postion', models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('medio', 'Medio'), ('delantero', 'Delantero')], default='Ninguna', max_length=30)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='players/picture/')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('dob', models.DateField()),
                ('stature', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=25, null=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='referee/picture/')),
                ('sex', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='Masculino', max_length=15)),
                ('referee_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbitros', to='league.League')),
            ],
            options={
                'verbose_name': 'Arbitro',
                'verbose_name_plural': 'Arbitros',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='rules_file')),
                ('league_rules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
            options={
                'verbose_name': 'Reglamento',
                'verbose_name_plural': 'Reglamentos',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('adress', models.CharField(blank=True, max_length=120, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('league_stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='teams/picture/')),
                ('category_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_categories', to='league.Category')),
                ('league_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_league', to='league.League')),
                ('stadium_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_stadium', to='league.Stadium')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='league.Team'),
        ),
        migrations.AddField(
            model_name='directive',
            name='league_directive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_directive', to='league.League'),
        ),
    ]
