# Generated by Django 2.0.12 on 2019-03-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Directiva',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='logo-league/')),
                ('email', models.EmailField(default='contact@micorreo.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='rules_file')),
                ('league_rules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
            options={
                'verbose_name': 'Reglamento',
                'verbose_name_plural': 'Reglamentos',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('adress', models.CharField(blank=True, max_length=120, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('league_stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.AddField(
            model_name='directive',
            name='league_directive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_directive', to='league.League'),
        ),
    ]
