# Generated by Django 2.0.12 on 2019-03-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_picture'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='teams.Team'),
        ),
    ]
