# Generated by Django 2.0.12 on 2019-03-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_stadium_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='teams',
        ),
    ]
