# Generated by Django 2.0.12 on 2019-03-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_auto_20190324_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('teams', models.ManyToManyField(blank=True, null=True, related_name='teams', to='teams.Team')),
            ],
            options={
                'verbose_name_plural': 'Torneos',
                'verbose_name': 'Torneo',
            },
        ),
    ]
