# Generated by Django 2.0.12 on 2019-03-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='teams.Team'),
        ),
    ]
