# Generated by Django 2.0.12 on 2019-03-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190322_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_player',
        ),
    ]
