# Generated by Django 2.0.12 on 2019-03-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_players'),
        ('players', '0004_remove_player_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='teams.Team'),
        ),
    ]
