# Generated by Django 2.0.12 on 2019-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='referee/picture/'),
        ),
    ]
