# Generated by Django 2.0.12 on 2019-03-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('league_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('stadium_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Stadium')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
