# Generated by Django 2.0.12 on 2019-03-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_team_player'),
        ('teams', '0002_team_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium_team',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='players.Player'),
        ),
    ]
