# Generated by Django 2.0.12 on 2019-03-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190323_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liga', to='league.League'),
        ),
    ]
